background = #282828
surface = #282828
surface_variant = #282828
primary = #458588
on_primary = #ffffff
primary_container = #458588
on_primary_container = #ffffff
text = #EBDBB2
text_muted = #EBDBB2
outline = #EBDBB2
outline_variant = #EBDBB2
