# ==============================================================================
# miqutoolkit color definitions for gruvbox-dark (dark)
# ==============================================================================
background = #282828
on_background = #EBDBB2
surface = #282828
on_surface = #EBDBB2
surface_variant = #282828
on_surface_variant = #EBDBB2
primary = #458588
on_primary = #ffffff
primary_container = #458588
on_primary_container = #ffffff
outline = #EBDBB2
outline_variant = #EBDBB2
backdrop = #28282880
