# ==============================================================================
# miqutoolkit color definitions for github-light-high-contrast (light)
# ==============================================================================
background = #ffffff
on_background = #010409
surface = #f6f8fa
on_surface = #010409
surface_variant = #f6f8fa
on_surface_variant = #010409
primary = #0969da
on_primary = #ffffff
primary_container = #0969da
on_primary_container = #ffffff
outline = #010409
outline_variant = #010409
backdrop = #ffffff80
