active_border_color      #AF3A03
inactive_border_color    #D5C4A1

background               #FBF1C7
foreground               #3C3836

selection_foreground     #FBF1C7
selection_background     #AF3A03

cursor                   #AF3A03
cursor_text_color        #FBF1C7

color0   #FBF1C7
color1   #9D0006
color2   #79740E
color3   #B57614
color4   #076678
color5   #8F3F71
color6   #427B58
color7   #7C6F64

color8   #928374
color9   #9D0006
color10  #79740E
color11  #B57614
color12  #076678
color13  #8F3F71
color14  #427B58
color15  #3C3836

active_tab_foreground    #FBF1C7
active_tab_background    #AF3A03
inactive_tab_foreground  #3C3836
inactive_tab_background  #EBDBB2
tab_bar_background       #FBF1C7
