background = #FBF1C7
surface = #FBF1C7
surface_variant = #FBF1C7
primary = #076678
on_primary = #ffffff
primary_container = #076678
on_primary_container = #ffffff
text = #3C3836
text_muted = #3C3836
outline = #3C3836
outline_variant = #3C3836
