# ==============================================================================
# miqutoolkit color definitions for gruvbox-light (light)
# ==============================================================================
background = #FBF1C7
on_background = #3C3836
surface = #FBF1C7
on_surface = #3C3836
surface_variant = #FBF1C7
on_surface_variant = #3C3836
primary = #076678
on_primary = #ffffff
primary_container = #076678
on_primary_container = #ffffff
outline = #3C3836
outline_variant = #3C3836
backdrop = #FBF1C780
