[global]
    frame_color = "#00394d"

[urgency_low]
    background = "#eff3f740"
    foreground = "#272e32"
    frame_color = "#444b50"

[urgency_normal]
    background = "#f6fafe40"
    foreground = "#000000"
    frame_color = "#00394d"

[urgency_critical]
    background = "#c3222040"
    foreground = "#ffffff"
    frame_color = "#700005"
