# General & Surface Colors
background #f6fce8
foreground #000000

# Cursor Colors
cursor #203b00
cursor_text_color #ffffff

# Selection Highlighting
selection_background #417100
selection_foreground #ffffff

# URL & Link Hovering
url_color #003d26

# Window Borders & Dividers
active_border_color #203b00
inactive_border_color #464c3e
bell_border_color #700005

# Tab Bar Colors
active_tab_background #203b00
active_tab_foreground #ffffff
inactive_tab_background #f0f5e2
inactive_tab_foreground #292f22
tab_bar_background #f6fce8

# Search Marks
mark1_foreground #ffffff
mark1_background #203b00
mark2_foreground #ffffff
mark2_background #003d26
mark3_foreground #ffffff
mark3_background #1f3a20

# 🎨 Complete Dynamic Matugen Light 16 ANSI Palette
# Black (Dark Text/Slate)
color0  #000000
color8  #464c3e

# Red (Errors, Git deleted)
color1  #700005
color9  #ffffff

# Green (Executables, .sh scripts, Git added)
color2  #1f3a20
color10 #ffffff

# Yellow / Gold (Warnings, Modded files, Archives)
color3  #003d26
color11 #ffffff

# Blue (Directories, Headers, Links)
color4  #203b00
color12 #ffffff

# Magenta / Purple (Keywords, Special files, Media)
color5  #84dd00
color13 #ffffff

# Cyan (Symlinks, Constants, Code strings)
color6  #1f3a20
color14 #ffffff

# White / Light Text
color7  #292f22
color15 #000000


background_opacity 0.50
