# General & Surface Colors
background #f6fafe
foreground #000000

# Cursor Colors
cursor #00394d
cursor_text_color #ffffff

# Selection Highlighting
selection_background #226c8b
selection_foreground #ffffff

# URL & Link Hovering
url_color #343050

# Window Borders & Dividers
active_border_color #00394d
inactive_border_color #444b50
bell_border_color #700005

# Tab Bar Colors
active_tab_background #00394d
active_tab_foreground #ffffff
inactive_tab_background #eff3f7
inactive_tab_foreground #272e32
tab_bar_background #f6fafe

# Search Marks
mark1_foreground #ffffff
mark1_background #00394d
mark2_foreground #ffffff
mark2_background #343050
mark3_foreground #ffffff
mark3_background #233741

# 🎨 Complete Dynamic Matugen Light 16 ANSI Palette
# Black (Dark Text/Slate)
color0  #000000
color8  #444b50

# Red (Errors, Git deleted)
color1  #700005
color9  #ffffff

# Green (Executables, .sh scripts, Git added)
color2  #233741
color10 #ffffff

# Yellow / Gold (Warnings, Modded files, Archives)
color3  #343050
color11 #ffffff

# Blue (Directories, Headers, Links)
color4  #00394d
color12 #ffffff

# Magenta / Purple (Keywords, Special files, Media)
color5  #8dcff2
color13 #ffffff

# Cyan (Symlinks, Constants, Code strings)
color6  #233741
color14 #ffffff

# White / Light Text
color7  #272e32
color15 #000000


background_opacity 0.25
