background = #f5fafe00
surface = #f5fafe
surface_variant = #d9e4eb
primary = #00394b
on_primary = #ffffff
primary_container = #006d8d
on_primary_container = #ffffff
text = #000000
text_muted = #242e34
outline = #414b51
outline_variant = #5b666c
