[manager]
cwd = { fg = "#46275a" }
hovered = { bg = "#e1d9e0", fg = "#000000" }
preview_hovered = { bg = "#faf0f8" }

find_keyword = { fg = "#46275a", bold = true }
find_position = { fg = "#50292b", italic = true }

marker_copied = { fg = "#3c3042", bg = "#6e6074" }
marker_cut = { fg = "#700005", bg = "#c32220" }
marker_marked = { fg = "#46275a", bg = "#79578e" }
marker_selected = { fg = "#50292b", bg = "#88585a" }

tab_active = { bg = "#46275a", fg = "#ffffff", bold = true }
tab_inactive = { bg = "#faf0f8", fg = "#312b33" }


count_copied = { fg = "#ffffff", bg = "#6e6074" }
count_cut = { fg = "#ffffff", bg = "#c32220" }
count_selected = { fg = "#ffffff", bg = "#79578e" }

border_symbol = "│"
border_style = { fg = "#4e4850" }

[status]
normal = { bg = "#46275a", fg = "#ffffff", bold = true }
select = { bg = "#3c3042", fg = "#ffffff", bold = true }
unset = { bg = "#700005", fg = "#ffffff", bold = true }
progress_label = { fg = "#000000", bold = true }
progress_normal = { fg = "#46275a", bg = "#fff7fc" }
progress_error = { fg = "#700005", bg = "#fff7fc" }

[mode]
normal_main = { bg = "#46275a", fg = "#ffffff", bold = true }
normal_alt = { bg = "#e1d9e0", fg = "#46275a" }
select_main = { bg = "#3c3042", fg = "#ffffff", bold = true }
select_alt = { bg = "#e1d9e0", fg = "#3c3042" }
unset_main = { bg = "#700005", fg = "#ffffff", bold = true }
unset_alt = { bg = "#e1d9e0", fg = "#700005" }

[input]
border = { fg = "#46275a" }
title = { fg = "#46275a" }
value = { fg = "#000000" }
selected = { bg = "#79578e" }

[select]
border = { fg = "#46275a" }
active = { fg = "#46275a", bold = true }
inactive = { fg = "#312b33" }

[tasks]
border = { fg = "#46275a" }
title = { fg = "#46275a" }
hovered = { bg = "#e1d9e0", fg = "#000000" }

[which]
mask = { bg = "#faf0f8" }
cand = { fg = "#46275a" }
rest = { fg = "#312b33" }
desc = { fg = "#000000" }
separator_style = { fg = "#4e4850" }

[help]
on = { fg = "#46275a" }
exec = { fg = "#50292b" }
desc = { fg = "#000000" }
hovered = { bg = "#e1d9e0", bold = true }
footer = { bg = "#fff7fc", fg = "#000000" }

[filetree]
folder = { fg = "#46275a" }
