[global]
    frame_color = "#a5c8ff"

[urgency_low]
    background = "#191c20"
    foreground = "#c3c6cf"
    frame_color = "#8d9199"

[urgency_normal]
    background = "#111318"
    foreground = "#e1e2e9"
    frame_color = "#a5c8ff"

[urgency_critical]
    background = "#93000a"
    foreground = "#ffdad6"
    frame_color = "#ffb4ab"
