[global]
    frame_color = "#adc6ff"

[urgency_low]
    background = "#191b22"
    foreground = "#c2c6d5"
    frame_color = "#8c909f"

[urgency_normal]
    background = "#11131a"
    foreground = "#e1e2eb"
    frame_color = "#adc6ff"

[urgency_critical]
    background = "#93000a"
    foreground = "#ffdad6"
    frame_color = "#ffb4ab"
