[global]
    frame_color = "#ffb869"

[urgency_low]
    background = "#1b1d0f"
    foreground = "#c7c9a7"
    frame_color = "#919374"

[urgency_normal]
    background = "#131408"
    foreground = "#e4e4ce"
    frame_color = "#ffb869"

[urgency_critical]
    background = "#93000a"
    foreground = "#ffdad6"
    frame_color = "#ffb4ab"
