[manager]
cwd = { fg = "#ffb869" }
hovered = { bg = "#2a2b1d", fg = "#e4e4ce" }
preview_hovered = { bg = "#1b1d0f" }

find_keyword = { fg = "#ffb869", bold = true }
find_position = { fg = "#c4cd7b", italic = true }

marker_copied = { fg = "#faba73", bg = "#673d00" }
marker_cut = { fg = "#ffb4ab", bg = "#93000a" }
marker_marked = { fg = "#ffb869", bg = "#673d00" }
marker_selected = { fg = "#c4cd7b", bg = "#444b05" }

tab_active = { bg = "#ffb869", fg = "#482900", bold = true }
tab_inactive = { bg = "#1b1d0f", fg = "#c7c9a7" }


count_copied = { fg = "#ffdcbb", bg = "#673d00" }
count_cut = { fg = "#ffdad6", bg = "#93000a" }
count_selected = { fg = "#ffdcbb", bg = "#673d00" }

border_symbol = "│"
border_style = { fg = "#919374" }

[status]
normal = { bg = "#ffb869", fg = "#482900", bold = true }
select = { bg = "#faba73", fg = "#482900", bold = true }
unset = { bg = "#ffb4ab", fg = "#690005", bold = true }
progress_label = { fg = "#e4e4ce", bold = true }
progress_normal = { fg = "#ffb869", bg = "#131408" }
progress_error = { fg = "#ffb4ab", bg = "#131408" }

[mode]
normal_main = { bg = "#ffb869", fg = "#482900", bold = true }
normal_alt = { bg = "#2a2b1d", fg = "#ffb869" }
select_main = { bg = "#faba73", fg = "#482900", bold = true }
select_alt = { bg = "#2a2b1d", fg = "#faba73" }
unset_main = { bg = "#ffb4ab", fg = "#690005", bold = true }
unset_alt = { bg = "#2a2b1d", fg = "#ffb4ab" }

[input]
border = { fg = "#ffb869" }
title = { fg = "#ffb869" }
value = { fg = "#e4e4ce" }
selected = { bg = "#673d00" }

[select]
border = { fg = "#ffb869" }
active = { fg = "#ffb869", bold = true }
inactive = { fg = "#c7c9a7" }

[tasks]
border = { fg = "#ffb869" }
title = { fg = "#ffb869" }
hovered = { bg = "#2a2b1d", fg = "#e4e4ce" }

[which]
mask = { bg = "#1b1d0f" }
cand = { fg = "#ffb869" }
rest = { fg = "#c7c9a7" }
desc = { fg = "#e4e4ce" }
separator_style = { fg = "#919374" }

[help]
on = { fg = "#ffb869" }
exec = { fg = "#c4cd7b" }
desc = { fg = "#e4e4ce" }
hovered = { bg = "#2a2b1d", bold = true }
footer = { bg = "#131408", fg = "#e4e4ce" }

[filetree]
folder = { fg = "#ffb869" }
