[global]
    frame_color = "#ffb86c"

[urgency_low]
    background = "#141414BF"
    foreground = "#9e9e9e"
    frame_color = "#444444"

[urgency_normal]
    background = "#1b1b1bBF"
    foreground = "#e0e0e0"
    frame_color = "#ffb86c"

[urgency_critical]
    background = "#332222BF"
    foreground = "#ff6e6e"
    frame_color = "#ff6e6e"
