[global]
    frame_color = "#5e81ac"

[urgency_low]
    background = "#d8dee9"
    foreground = "#4c566a"
    frame_color = "#e5e9f0"

[urgency_normal]
    background = "#eceff4"
    foreground = "#2e3440"
    frame_color = "#5e81ac"

[urgency_critical]
    background = "#e5e9f0"
    foreground = "#bf616a"
    frame_color = "#bf616a"
