active_border_color      #5E81AC
inactive_border_color    #D8DEE9

background               #ECEFF4
foreground               #2E3440

selection_foreground     #ECEFF4
selection_background     #5E81AC

cursor                   #5E81AC
cursor_text_color        #ECEFF4

color0   #3B4252
color1   #BF616A
color2   #A3BE8C
color3   #EBCB8B
color4   #5E81AC
color5   #B48EAD
color6   #88C0D0
color7   #E5E9F0

color8   #4C566A
color9   #BF616A
color10  #A3BE8C
color11  #EBCB8B
color12  #5E81AC
color13  #B48EAD
color14  #88C0D0
color15  #2E3440

active_tab_foreground    #ECEFF4
active_tab_background    #5E81AC
inactive_tab_foreground  #2E3440
inactive_tab_background  #E5E9F0
tab_bar_background       #ECEFF4
