background = #ECEFF4
surface = #3B4252
surface_variant = #3B4252
primary = #5E81AC
on_primary = #ffffff
primary_container = #5E81AC
on_primary_container = #ffffff
text = #2E3440
text_muted = #2E3440
outline = #2E3440
outline_variant = #2E3440
