# ==============================================================================
# miqutoolkit color definitions for nord-light (light)
# ==============================================================================
background = #ECEFF4
on_background = #2E3440
surface = #3B4252
on_surface = #2E3440
surface_variant = #3B4252
on_surface_variant = #2E3440
primary = #5E81AC
on_primary = #ffffff
primary_container = #5E81AC
on_primary_container = #ffffff
outline = #2E3440
outline_variant = #2E3440
backdrop = #ECEFF480
