background = #2E3440
surface = #3B4252
surface_variant = #3B4252
primary = #81A1C1
on_primary = #ffffff
primary_container = #81A1C1
on_primary_container = #ffffff
text = #D8DEE9
text_muted = #D8DEE9
outline = #D8DEE9
outline_variant = #D8DEE9
