# ==============================================================================
# miqutoolkit color definitions for nord-dark (dark)
# ==============================================================================
background = #2E3440
on_background = #D8DEE9
surface = #3B4252
on_surface = #D8DEE9
surface_variant = #3B4252
on_surface_variant = #D8DEE9
primary = #81A1C1
on_primary = #ffffff
primary_container = #81A1C1
on_primary_container = #ffffff
outline = #D8DEE9
outline_variant = #D8DEE9
backdrop = #2E344080
