# ==============================================================================
# miqutoolkit color definitions for catppuccin-mocha (dark)
# ==============================================================================
background = #1E1E2E
on_background = #CDD6F4
surface = #45475A
on_surface = #CDD6F4
surface_variant = #45475A
on_surface_variant = #CDD6F4
primary = #89B4FA
on_primary = #ffffff
primary_container = #89B4FA
on_primary_container = #ffffff
outline = #CDD6F4
outline_variant = #CDD6F4
backdrop = #1E1E2E80
