[global]
    frame_color = "#268bd2"

[urgency_low]
    background = "#eee8d5"
    foreground = "#657b83"
    frame_color = "#93a1a1"

[urgency_normal]
    background = "#fdf6e3"
    foreground = "#073642"
    frame_color = "#268bd2"

[urgency_critical]
    background = "#fdf6e3"
    foreground = "#dc322f"
    frame_color = "#dc322f"
