# ==============================================================================
# miqutoolkit color definitions for solarized-light-contrast (light)
# ==============================================================================
background = #fdf6e3
on_background = #002b36
surface = #eee8d5
on_surface = #002b36
surface_variant = #eee8d5
on_surface_variant = #002b36
primary = #268bd2
on_primary = #ffffff
primary_container = #268bd2
on_primary_container = #ffffff
outline = #002b36
outline_variant = #002b36
backdrop = #fdf6e380
