[global]
    frame_color = "#78dce8"

[urgency_low]
    background = "#221f22"
    foreground = "#939293"
    frame_color = "#5b585c"

[urgency_normal]
    background = "#2d2a2e"
    foreground = "#fcfcfa"
    frame_color = "#78dce8"

[urgency_critical]
    background = "#403c40"
    foreground = "#ff6188"
    frame_color = "#ff6188"
