# ==============================================================================
# miqutoolkit color definitions for monokai-pro (dark)
# ==============================================================================
background = #19181a
on_background = #fcfcfa
surface = #221f22
on_surface = #fcfcfa
surface_variant = #221f22
on_surface_variant = #fcfcfa
primary = #fc9867
on_primary = #ffffff
primary_container = #fc9867
on_primary_container = #ffffff
outline = #fcfcfa
outline_variant = #fcfcfa
backdrop = #19181a80
