background = #19181a
surface = #221f22
surface_variant = #221f22
primary = #fc9867
on_primary = #ffffff
primary_container = #fc9867
on_primary_container = #ffffff
text = #fcfcfa
text_muted = #fcfcfa
outline = #fcfcfa
outline_variant = #fcfcfa
