background = #FDF6E3
surface = #073642
surface_variant = #073642
primary = #268BD2
on_primary = #ffffff
primary_container = #268BD2
on_primary_container = #ffffff
text = #657B83
text_muted = #657B83
outline = #657B83
outline_variant = #657B83
