# ==============================================================================
# miqutoolkit color definitions for warm-light (light)
# ==============================================================================
background = #FDF6E3
on_background = #657B83
surface = #073642
on_surface = #657B83
surface_variant = #073642
on_surface_variant = #657B83
primary = #268BD2
on_primary = #ffffff
primary_container = #268BD2
on_primary_container = #ffffff
outline = #657B83
outline_variant = #657B83
backdrop = #FDF6E380
