background = #181824
surface = #21222c
surface_variant = #21222c
primary = #bd93f9
on_primary = #ffffff
primary_container = #bd93f9
on_primary_container = #ffffff
text = #f8f8f2
text_muted = #f8f8f2
outline = #f8f8f2
outline_variant = #f8f8f2
