# ==============================================================================
# miqutoolkit color definitions for dracula-contrast (dark)
# ==============================================================================
background = #181824
on_background = #f8f8f2
surface = #21222c
on_surface = #f8f8f2
surface_variant = #21222c
on_surface_variant = #f8f8f2
primary = #bd93f9
on_primary = #ffffff
primary_container = #bd93f9
on_primary_container = #ffffff
outline = #f8f8f2
outline_variant = #f8f8f2
backdrop = #18182480
