[global]
    frame_color = "#363600"

[urgency_low]
    background = "#eff3fb"
    foreground = "#242e37"
    frame_color = "#414b55"

[urgency_normal]
    background = "#f7f9ff"
    foreground = "#000000"
    frame_color = "#363600"

[urgency_critical]
    background = "#c32220"
    foreground = "#ffffff"
    frame_color = "#700005"
