[global]
    frame_color = "#46275a"

[urgency_low]
    background = "#faf0f8"
    foreground = "#312b33"
    frame_color = "#4e4850"

[urgency_normal]
    background = "#fff7fc"
    foreground = "#000000"
    frame_color = "#46275a"

[urgency_critical]
    background = "#c32220"
    foreground = "#ffffff"
    frame_color = "#700005"
