[global]
    frame_color = "#00394b"

[urgency_low]
    background = "#eff4f7"
    foreground = "#242e34"
    frame_color = "#414b51"

[urgency_normal]
    background = "#f5fafe"
    foreground = "#000000"
    frame_color = "#00394b"

[urgency_critical]
    background = "#c32220"
    foreground = "#ffffff"
    frame_color = "#700005"
