# General & Surface Colors
background #fff7fc
foreground #000000

# Cursor Colors
cursor #46275a
cursor_text_color #ffffff

# Selection Highlighting
selection_background #79578e
selection_foreground #ffffff

# URL & Link Hovering
url_color #50292b

# Window Borders & Dividers
active_border_color #46275a
inactive_border_color #4e4850
bell_border_color #700005

# Tab Bar Colors
active_tab_background #46275a
active_tab_foreground #ffffff
inactive_tab_background #faf0f8
inactive_tab_foreground #312b33
tab_bar_background #fff7fc

# Search Marks
mark1_foreground #ffffff
mark1_background #46275a
mark2_foreground #ffffff
mark2_background #50292b
mark3_foreground #ffffff
mark3_background #3c3042

# 🎨 Complete Dynamic Matugen Light 16 ANSI Palette
# Black (Dark Text/Slate)
color0  #000000
color8  #4e4850

# Red (Errors, Git deleted)
color1  #700005
color9  #ffffff

# Green (Executables, .sh scripts, Git added)
color2  #3c3042
color10 #ffffff

# Yellow / Gold (Warnings, Modded files, Archives)
color3  #50292b
color11 #ffffff

# Blue (Directories, Headers, Links)
color4  #46275a
color12 #ffffff

# Magenta / Purple (Keywords, Special files, Media)
color5  #e0b8f6
color13 #ffffff

# Cyan (Symlinks, Constants, Code strings)
color6  #3c3042
color14 #ffffff

# White / Light Text
color7  #312b33
color15 #000000

