background = #fff7fc
surface = #fff7fc
surface_variant = #eadfea
primary = #46275a
on_primary = #ffffff
primary_container = #79578e
on_primary_container = #ffffff
text = #000000
text_muted = #312b33
outline = #4e4850
outline_variant = #6a626b
