[manager]
cwd = { fg = "#363600" }
hovered = { bg = "#d7dbe3", fg = "#000000" }
preview_hovered = { bg = "#eff3fb" }

find_keyword = { fg = "#363600", bold = true }
find_position = { fg = "#003758", italic = true }

marker_copied = { fg = "#422c49", bg = "#755c7c" }
marker_cut = { fg = "#700005", bg = "#c32220" }
marker_marked = { fg = "#363600", bg = "#676813" }
marker_selected = { fg = "#003758", bg = "#3e688c" }

tab_active = { bg = "#363600", fg = "#ffffff", bold = true }
tab_inactive = { bg = "#eff3fb", fg = "#242e37" }


count_copied = { fg = "#ffffff", bg = "#755c7c" }
count_cut = { fg = "#ffffff", bg = "#c32220" }
count_selected = { fg = "#ffffff", bg = "#676813" }

border_symbol = "│"
border_style = { fg = "#414b55" }

[status]
normal = { bg = "#363600", fg = "#ffffff", bold = true }
select = { bg = "#422c49", fg = "#ffffff", bold = true }
unset = { bg = "#700005", fg = "#ffffff", bold = true }
progress_label = { fg = "#000000", bold = true }
progress_normal = { fg = "#363600", bg = "#f7f9ff" }
progress_error = { fg = "#700005", bg = "#f7f9ff" }

[mode]
normal_main = { bg = "#363600", fg = "#ffffff", bold = true }
normal_alt = { bg = "#d7dbe3", fg = "#363600" }
select_main = { bg = "#422c49", fg = "#ffffff", bold = true }
select_alt = { bg = "#d7dbe3", fg = "#422c49" }
unset_main = { bg = "#700005", fg = "#ffffff", bold = true }
unset_alt = { bg = "#d7dbe3", fg = "#700005" }

[input]
border = { fg = "#363600" }
title = { fg = "#363600" }
value = { fg = "#000000" }
selected = { bg = "#676813" }

[select]
border = { fg = "#363600" }
active = { fg = "#363600", bold = true }
inactive = { fg = "#242e37" }

[tasks]
border = { fg = "#363600" }
title = { fg = "#363600" }
hovered = { bg = "#d7dbe3", fg = "#000000" }

[which]
mask = { bg = "#eff3fb" }
cand = { fg = "#363600" }
rest = { fg = "#242e37" }
desc = { fg = "#000000" }
separator_style = { fg = "#414b55" }

[help]
on = { fg = "#363600" }
exec = { fg = "#003758" }
desc = { fg = "#000000" }
hovered = { bg = "#d7dbe3", bold = true }
footer = { bg = "#f7f9ff", fg = "#000000" }

[filetree]
folder = { fg = "#363600" }
