[manager]
cwd = { fg = "#00394d" }
hovered = { bg = "#d7dce0", fg = "#000000" }
preview_hovered = { bg = "#eff3f7" }

find_keyword = { fg = "#00394d", bold = true }
find_position = { fg = "#343050", italic = true }

marker_copied = { fg = "#233741", bg = "#546773" }
marker_cut = { fg = "#700005", bg = "#c32220" }
marker_marked = { fg = "#00394d", bg = "#226c8b" }
marker_selected = { fg = "#343050", bg = "#656184" }

tab_active = { bg = "#00394d", fg = "#ffffff", bold = true }
tab_inactive = { bg = "#eff3f7", fg = "#272e32" }


count_copied = { fg = "#ffffff", bg = "#546773" }
count_cut = { fg = "#ffffff", bg = "#c32220" }
count_selected = { fg = "#ffffff", bg = "#226c8b" }

border_symbol = "│"
border_style = { fg = "#444b50" }

[status]
normal = { bg = "#00394d", fg = "#ffffff", bold = true }
select = { bg = "#233741", fg = "#ffffff", bold = true }
unset = { bg = "#700005", fg = "#ffffff", bold = true }
progress_label = { fg = "#000000", bold = true }
progress_normal = { fg = "#00394d", bg = "#f6fafe" }
progress_error = { fg = "#700005", bg = "#f6fafe" }

[mode]
normal_main = { bg = "#00394d", fg = "#ffffff", bold = true }
normal_alt = { bg = "#d7dce0", fg = "#00394d" }
select_main = { bg = "#233741", fg = "#ffffff", bold = true }
select_alt = { bg = "#d7dce0", fg = "#233741" }
unset_main = { bg = "#700005", fg = "#ffffff", bold = true }
unset_alt = { bg = "#d7dce0", fg = "#700005" }

[input]
border = { fg = "#00394d" }
title = { fg = "#00394d" }
value = { fg = "#000000" }
selected = { bg = "#226c8b" }

[select]
border = { fg = "#00394d" }
active = { fg = "#00394d", bold = true }
inactive = { fg = "#272e32" }

[tasks]
border = { fg = "#00394d" }
title = { fg = "#00394d" }
hovered = { bg = "#d7dce0", fg = "#000000" }

[which]
mask = { bg = "#eff3f7" }
cand = { fg = "#00394d" }
rest = { fg = "#272e32" }
desc = { fg = "#000000" }
separator_style = { fg = "#444b50" }

[help]
on = { fg = "#00394d" }
exec = { fg = "#343050" }
desc = { fg = "#000000" }
hovered = { bg = "#d7dce0", bold = true }
footer = { bg = "#f6fafe", fg = "#000000" }

[filetree]
folder = { fg = "#00394d" }
