background = #EFF1F5
surface = #5C5F77
surface_variant = #5C5F77
primary = #1E66F5
on_primary = #ffffff
primary_container = #1E66F5
on_primary_container = #ffffff
text = #4C4F69
text_muted = #4C4F69
outline = #4C4F69
outline_variant = #4C4F69
