# ==============================================================================
# miqutoolkit color definitions for catppuccin-latte (light)
# ==============================================================================
background = #EFF1F5
on_background = #4C4F69
surface = #5C5F77
on_surface = #4C4F69
surface_variant = #5C5F77
on_surface_variant = #4C4F69
primary = #1E66F5
on_primary = #ffffff
primary_container = #1E66F5
on_primary_container = #ffffff
outline = #4C4F69
outline_variant = #4C4F69
backdrop = #EFF1F580
